FROM mcr.microsoft.com/dotnet/sdk:9.0

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    openssh-client \
    && rm -rf /var/lib/apt/lists/* 

RUN dotnet tool install --global dotnet-ef --version 9.*
ENV PATH="$PATH:/root/.dotnet/tools"